INSERT INTO public.warehouse ( name, numberofstorageshelves) VALUES ( 'Alapertelmezett Raktar', 5);
INSERT INTO public.warehouse ( name, numberofstorageshelves) VALUES ( 'Masodik Raktar', 5);
INSERT INTO public.warehouse ( name, numberofstorageshelves) VALUES ( 'Harmadik Raktar', 3);
INSERT INTO public.warehouse ( name, numberofstorageshelves) VALUES ( 'Tartalekos Raktar', 2);
INSERT INTO public.warehouse ( name, numberofstorageshelves) VALUES ( 'werwer', 2);
INSERT INTO public.warehouse ( name, numberofstorageshelves) VALUES ( 'rrrr', 2);
INSERT INTO public.warehouse ( name, numberofstorageshelves) VALUES ( 'teszt', 3);
INSERT INTO public.warehouse ( name, numberofstorageshelves) VALUES ( 'teszter', 1);
INSERT INTO public.warehouse ( name, numberofstorageshelves) VALUES ( 'teszt3', 4);

INSERT INTO public.storage (numberofshelves, height, width, depth, warehouseid, loadcapacity) VALUES (4, 5, 12, 1, 1, 2500);
INSERT INTO public.storage (numberofshelves, height, width, depth, warehouseid, loadcapacity) VALUES (4, 5, 12, 1, 1, 2500);
INSERT INTO public.storage (numberofshelves, height, width, depth, warehouseid, loadcapacity) VALUES (4, 5, 12, 1, 1, 2500);
INSERT INTO public.storage (numberofshelves, height, width, depth, warehouseid, loadcapacity) VALUES (4, 5, 12, 1, 1, 2500);
INSERT INTO public.storage (numberofshelves, height, width, depth, warehouseid, loadcapacity) VALUES (4, 5, 12, 1, 1, 2500);
INSERT INTO public.storage (numberofshelves, height, width, depth, warehouseid, loadcapacity) VALUES (4, 5, 10, 1, 2, 3000);
INSERT INTO public.storage (numberofshelves, height, width, depth, warehouseid, loadcapacity) VALUES (4, 5, 10, 1, 2, 3000);
INSERT INTO public.storage (numberofshelves, height, width, depth, warehouseid, loadcapacity) VALUES (4, 5, 10, 1, 2, 3000);
INSERT INTO public.storage (numberofshelves, height, width, depth, warehouseid, loadcapacity) VALUES (4, 5, 10, 1, 2, 3000);
INSERT INTO public.storage (numberofshelves, height, width, depth, warehouseid, loadcapacity) VALUES ( 4, 5, 10, 1, 2, 3000);
INSERT INTO public.storage (numberofshelves, height, width, depth, warehouseid, loadcapacity) VALUES ( 3, 5, 7, 1, 3, 1800);
INSERT INTO public.storage (numberofshelves, height, width, depth, warehouseid, loadcapacity) VALUES ( 3, 5, 7, 1, 3, 1800);
INSERT INTO public.storage (numberofshelves, height, width, depth, warehouseid, loadcapacity) VALUES ( 3, 5, 7, 1, 3, 1800);
INSERT INTO public.storage (numberofshelves, height, width, depth, warehouseid, loadcapacity) VALUES ( 2, 5, 4, 1, 4, 1000);
INSERT INTO public.storage (numberofshelves, height, width, depth, warehouseid, loadcapacity) VALUES ( 2, 5, 4, 1, 4, 1000);
INSERT INTO public.storage (numberofshelves, height, width, depth, warehouseid, loadcapacity) VALUES ( 4, 4, 4, 4, 5, 12);
INSERT INTO public.storage (numberofshelves, height, width, depth, warehouseid, loadcapacity) VALUES ( 1, 1, 1, 1, 7, 1);
INSERT INTO public.storage (numberofshelves, height, width, depth, warehouseid, loadcapacity) VALUES ( 4, 4, 4, 4, 9, 12);
INSERT INTO public.storage (numberofshelves, height, width, depth, warehouseid, loadcapacity) VALUES ( 4, 4, 4, 4, 9, 12);
INSERT INTO public.storage (numberofshelves, height, width, depth, warehouseid, loadcapacity) VALUES ( 4, 4, 4, 4, 9, 12);
INSERT INTO public.storage (numberofshelves, height, width, depth, warehouseid, loadcapacity) VALUES ( 1, 1, 1, 1, 7, 1);
INSERT INTO public.storage (numberofshelves, height, width, depth, warehouseid, loadcapacity) VALUES ( 2, 3, 5, 5, 9, 2);
INSERT INTO public.storage (numberofshelves, height, width, depth, warehouseid, loadcapacity) VALUES ( 4, 4, 4, 4, 8, 12);
INSERT INTO public.storage (numberofshelves, height, width, depth, warehouseid, loadcapacity) VALUES ( 20, 20, 20, 20, 7, 20);
INSERT INTO public.storage (numberofshelves, height, width, depth, warehouseid, loadcapacity) VALUES ( 12, 12, 120, 120, 9, 120);
INSERT INTO public.storage (numberofshelves, height, width, depth, warehouseid, loadcapacity) VALUES ( 10, 10, 10, 20, 5, 20);
INSERT INTO public.storage (numberofshelves, height, width, depth, warehouseid, loadcapacity) VALUES ( 10, 20, 30, 40, 5, 50);

INSERT INTO public.manufacturer ( name, description) VALUES ( 'HP', 'Hewlett Packard');
INSERT INTO public.manufacturer ( name, description) VALUES ( 'Dell', 'Dell Corporation');
INSERT INTO public.manufacturer ( name, description) VALUES ( 'Apple', 'Apple Inc.');
INSERT INTO public.manufacturer ( name, description) VALUES ( 'Western Digital', 'Western Digital Inc.');
INSERT INTO public.manufacturer ( name, description) VALUES ( 'Seagate', 'Seagate Inc.');


INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES (1, 1, 12, 1, 500);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES (1, 1, 12, 1, 500);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES (1, 1, 12, 1, 500);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES (1, 1, 12, 1, 1000);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES (2, 1, 12, 1, 500);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES (2, 1, 12, 1, 500);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES (2, 1, 12, 1, 500);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES (2, 1, 12, 1, 1000);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES (3, 1, 12, 1, 500);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 3, 1, 12, 1, 500);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 3, 1, 12, 1, 500);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 3, 1, 12, 1, 1000);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 4, 1, 12, 1, 500);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 4, 1, 12, 1, 500);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 4, 1, 12, 1, 500);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 4, 1, 12, 1, 1000);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 5, 1, 12, 1, 500);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 5, 1, 12, 1, 500);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 5, 1, 12, 1, 500);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 5, 1, 12, 1, 1000);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 6, 1, 10, 1, 500);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 6, 1, 10, 1, 500);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 6, 1, 10, 1, 1000);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 6, 1, 10, 1, 1000);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 7, 1, 10, 1, 500);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 7, 1, 10, 1, 500);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 7, 1, 10, 1, 1000);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 7, 1, 10, 1, 1000);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 8, 1, 10, 1, 500);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 8, 1, 10, 1, 500);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 8, 1, 10, 1, 1000);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 8, 1, 10, 1, 1000);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 9, 1, 10, 1, 500);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 9, 1, 10, 1, 500);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 9, 1, 10, 1, 1000);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 9, 1, 10, 1, 1000);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 10, 1, 10, 1, 500);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 10, 1, 10, 1, 500);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 10, 1, 10, 1, 1000);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 10, 1, 10, 1, 1000);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 11, 1, 7, 1, 600);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 11, 1, 7, 1, 600);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 11, 1, 7, 1, 600);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 12, 1, 7, 1, 600);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 12, 1, 7, 1, 600);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 12, 1, 7, 1, 600);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 13, 1, 7, 1, 600);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 13, 1, 7, 1, 600);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 13, 1, 7, 1, 600);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 14, 1, 4, 1, 500);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 14, 1, 4, 1, 500);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 15, 1, 4, 1, 500);
INSERT INTO public.shelf ( storageid, height, width, depth, loadcapacity) VALUES ( 15, 1, 4, 1, 500);
